### ISSUE TITLE
consider make a logo for this library

### ISSUE THREAD

**Issue by beenotung** [matthewp/corset#167]
If you lack designer help, may try to use stable diffusion to generate the logo. I tried that for my library and it's an easy process although it takes time to iterate when your idea isn't solid.

A hosted online model that doesn't require account to get started: https://huggingface.co/spaces/huggingface/diffuse-the-rest

**Comment by matthewp** [comment]
Thank you for the suggestion. I'm actually going to be rebranding the project soon, see https://space.matthewphillips.info/posts/corset-update/. Once that is done I'll likely think about a logo.
